echo Testing timeout parameters
echo XXX when there are commands that will time out, this should test
echo XXX that with very short timeouts.

get /reader/commandTimeout

set /reader/commandTimeout 1500
get /reader/commandTimeout

set /reader/commandTimeout 100
get /reader/commandTimeout


get /reader/transportTimeout

set /reader/transportTimeout 1500
get /reader/transportTimeout

set /reader/transportTimeout 100
get /reader/transportTimeout
