echo Baud rate tests

get /reader/baudRate # Check default

# For each possible rate that reasonably works on a conventional 
# serial port, set the rate and then run some command that requires
# communication. We'll use read power, and set it first so that we
# know what the result will be.

set /reader/radio/readPower 3000

set /reader/baudRate 9600
get /reader/baudRate
get /reader/radio/readPower

set /reader/baudRate 19200
get /reader/baudRate
get /reader/radio/readPower

set /reader/baudRate 38400
get /reader/baudRate
get /reader/radio/readPower

set /reader/baudRate 57600
get /reader/baudRate
get /reader/radio/readPower

set /reader/baudRate 230400
get /reader/baudRate
get /reader/radio/readPower

# Do this one last, so we leave it at the default rate.
set /reader/baudRate 115200
get /reader/baudRate
get /reader/radio/readPower

