echo Port settling time

get /reader/antenna/portList
get /reader/antenna/settlingTimeList

set /reader/antenna/settlingTimeList [[1,100]]
get /reader/antenna/settlingTimeList

echo Test clearing an entry with a 0 value
set /reader/antenna/settlingTimeList [[1,0]]
get /reader/antenna/settlingTimeList

echo Test multiple settings
set /reader/antenna/settlingTimeList [[1,100],[2,200]]
get /reader/antenna/settlingTimeList

echo Test order dependance of multuple settings
set /reader/antenna/settlingTimeList [[2,200],[1,100]]
get /reader/antenna/settlingTimeList

echo Test removing entries implicitly
set /reader/antenna/settlingTimeList [[2,300]]
get /reader/antenna/settlingTimeList

echo Test setting for nonexistent ports
set /reader/antenna/settlingTimeList [[255,300]]

echo Reset to default
set /reader/antenna/settlingTimeList []
get /reader/antenna/settlingTimeList

