echo Testing tag locking

get /reader/radio/temperature

set /reader/gen2/session S0
set /reader/gen2/accessPassword 0
# Limit reader range for these potentially annoying operations
set /reader/radio/writePower 2000
set /reader/radio/readPower 2000

echo Create tag with known EPC and password
writeepc EPC:0123456789ABCDEF01234567
set /reader/read/plan [GEN2,[],EPC:0123456789ABCDEF01234567,1]
read 100
set /reader/read/plan [GEN2,[],NULL,1]

writememwords 0 2 words:12345678 EPC:0123456789ABCDEF01234567
readmemwords 0 2 2 EPC:0123456789ABCDEF01234567

echo Locking tag
set /reader/gen2/accessPassword 0x12345678
lock Gen2.LockAction:EPC_LOCK EPC:0123456789ABCDEF01234567
set /reader/gen2/accessPassword 0
set /reader/commandTimeout 1000

echo Try a write that should now fail
writememwords 1 2 words:999999998888888877777777 EPC:0123456789ABCDEF01234567

echo This should find a tag:
set /reader/read/plan [GEN2,[],EPC:0123456789ABCDEF01234567,1]
read 100
echo And this should not:
set /reader/read/plan [GEN2,[],EPC:999999998888888877777777,1]
read 100
set /reader/read/plan [GEN2,[],NULL,1]

set /reader/gen2/accessPassword 0x12345678
lock Gen2.LockAction:EPC_UNLOCK EPC:0123456789ABCDEF01234567
set /reader/gen2/accessPassword 0

echo Now the EPC write should succeed
writememwords 1 2 words:999999998888888877777777 EPC:0123456789ABCDEF01234567

echo This should not find a tag:
set /reader/read/plan [GEN2,[],EPC:0123456789ABCDEF01234567,1]
read 100
echo And this should:
set /reader/read/plan [GEN2,[],EPC:999999998888888877777777,1]
read 100
set /reader/read/plan [GEN2,[],NULL,1]

writememwords 1 2 words:0123456789ABCDEF01234567 EPC:999999998888888877777777 


echo Check that the access password is unreadable when locked.
set /reader/gen2/accessPassword 0x12345678
lock Gen2.LockAction:EPC_LOCK,ACCESS_LOCK EPC:0123456789ABCDEF01234567
set /reader/gen2/accessPassword 0
readmemwords 0 2 2 EPC:0123456789ABCDEF01234567 EPC:0123456789ABCDEF01234567
echo Check that the EPC was also locked
writememwords 1 2 words:999999998888888877777777 EPC:0123456789ABCDEF01234567
echo This should find a tag:
set /reader/read/plan [GEN2,[],EPC:0123456789ABCDEF01234567,1]
read 100
echo And this should not:
set /reader/read/plan [GEN2,[],EPC:999999998888888877777777,1]
read 100
set /reader/read/plan [GEN2,[],NULL,1]

echo Now really reset everything
set /reader/gen2/accessPassword 0x12345678
lock Gen2.LockAction:EPC_UNLOCK,ACCESS_UNLOCK EPC:0123456789ABCDEF01234567
writememwords 0 2 words:00000000 EPC:0123456789ABCDEF01234567

set /reader/gen2/accessPassword 0
readmemwords 0 2 2 EPC:0123456789ABCDEF01234567
echo Restored EPC and access password


