echo Power mode tests

# XXX really just tests paramater parsing, printing, and value persistence

# Check default
get /reader/powerMode

set /reader/powerMode MAXSAVE
get /reader/powerMode

set /reader/powerMode MEDSAVE
get /reader/powerMode

set /reader/powerMode MINSAVE
get /reader/powerMode

set /reader/powerMode FULL
get /reader/powerMode

# Bogus
set /reader/powerMode ABCDE
set /reader/powerMode NULL

